config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :taxon_groups do
      member do
        get :positions, to: 'taxon_groups#positions'
        patch :positions, to: 'taxon_groups#update_positions'
      end
    end
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  has_many :taxon_group_memberships, class_name: 'Spree::TaxonGroupMembership', dependent: :destroy
  has_many :taxon_groups, through: :taxon_group_memberships
end

app/models/spree/taxon_group.rb
module Spree
  class TaxonGroup < ActiveRecord::Base
    validates :name, presence: true
    validates :key, presence: true

    has_many :taxon_group_memberships, class_name: 'Spree::TaxonGroupMembership', dependent: :destroy
    has_many :taxons, -> { order 'spree_taxon_group_memberships.position' }, through: :taxon_group_memberships
  end
end

app/models/spree/taxon_group_membership.rb
module Spree
  class TaxonGroupMembership < ActiveRecord::Base
    validates :taxon_group, presence: true
    validates :taxon, presence: true
    validates :position, presence: true, numericality: { only_integer: true }

    belongs_to :taxon_group
    belongs_to :taxon
  end
end

app/controllers/spree/admin/taxon_groups_controller.rb
module Spree
  module Admin
    class TaxonGroupsController < ResourceController
      before_action :load_taxons, only: [:new, :edit, :create]
      before_action :load_taxon_group, only: [:update_positions]

      def positions
        @taxon_group_memberships = @taxon_group.taxon_group_memberships.order(:position)
      end

      def update_positions
        begin
          update_taxon_group_memership_positions
          flash[:success] = flash_message_for(@taxon_group, :successfully_updated)
        rescue => e
          flash[:error] = e.message
        end

        respond_with(@taxon_group) do |format|
          format.html { redirect_to positions_admin_taxon_group_url(@taxon_group) }
          format.json { render json: @taxon_group.to_json }
        end
      end

      private

      def load_taxons
        @taxons = Spree::Taxon.all
      end

      def load_taxon_group
        @taxon_group = Spree::TaxonGroup.find(params[:id])
      end

      def update_taxon_group_memership_positions
        update_positions_params.each do |id, position|
          Spree::TaxonGroupMembership.update(id, position: position)
        end
      end

      def update_positions_params
        params.require(:taxon_group_membership).require(:position)
      end
    end
  end
end

app/helpers/spree/frontend_helper_decorator.rb
Spree::FrontendHelper.class_eval do
  def taxon_group_tree(taxon_group, current_taxon)
    content_tag :div, class: 'list-group' do
      taxon_group.taxon_group_memberships.sort_by(&:position).map do |membership|
        css_class = (current_taxon.eql? membership.taxon) ? 'list-group-item active' : 'list-group-item'
        link_to(membership.taxon.name, seo_url(membership.taxon), class: css_class)
      end.join("\n").html_safe
    end
  end
end

app/views/spree/admin/taxon_groups/_form.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_resource_list, resource: plural_resource_name(Spree::TaxonGroup)), spree.admin_taxon_groups_path, icon: 'arrow-left', class: 'btn-primary' %>
<% end %>

<%= form_for [:admin, resource] do |f| %>

  <div class="row" data-hook="admin_page_form_fields">
    <div class="form-group">
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.error_message_on :name %>
    </div>

    <div class="form-group">
      <%= f.label :key, Spree.t(:key) %> <span class="required">*</span>
      <%= f.text_field :key, class: 'form-control' %>
      <%= f.error_message_on :key %>
    </div>
  </div>

  <div class="row" data-hook="admin_page_form_fields">
    <div class="form-group">
      <table class="table table-hover">
        <thead>
          <tr data-hook="taxons_header">
            <th></th>
            <th><%= Spree.t(:taxon_name) %></th>
            <th><%= Spree.t(:path) %></th>
          </tr>
        </thead>
        <tbody>
          <% @taxons.each do |taxon| %>
            <tr id="<%= spree_dom_id(taxon) %>" data-hook="taxons_row">
              <td><%= check_box_tag('taxon_group[taxon_ids][]', taxon.id, taxon.id.in?(resource.taxons.pluck(:id))) %></td>
              <td><%= taxon.name %></td>
              <td><%= taxon_path taxon %></td>
            </tr>
          <% end %>
          <% if @taxons.empty? %>
            <tr data-hook="taxons_none"><td colspan="3"><%= Spree.t(:none) %>.</td></tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <script>
    $(function() {
      // Checks a taxon's row checkbox on click
      $('[data-hook="taxons_row"]').on('click', function(e) {
        // If checkbox, do nothing (prevent double select)
        if ($(event.target).context.type == 'checkbox' ) {
          return;
        }
        //debugger;
        var checkbox = $(this).find('input:checkbox');
        checkbox.prop("checked", !checkbox.prop("checked"));
      });
    });
  </script>

  <%= render "spree/admin/shared/#{resource.new_record? ? 'new' : 'edit'}_resource_links" %>

<% end %>

app/views/spree/admin/taxon_groups/_form_positions.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_resource_list, resource: plural_resource_name(Spree::TaxonGroup)), spree.admin_taxon_groups_path, icon: 'arrow-left', class: 'btn-primary' %>
<% end %>

<%= form_for [:admin, resource], url: positions_admin_taxon_group_path(resource.id) do |f| %>

  <div class="row" data-hook="admin_page_form_fields">
    <div class="form-group">
      <table class="table table-hover">
        <thead>
          <tr data-hook="taxons_header">
            <th></th>
            <th><%= Spree.t(:taxon_name) %></th>
            <th><%= Spree.t(:path) %></th>
          </tr>
        </thead>
        <tbody>
          <% @taxon_group_memberships.each do |membership| %>
            <tr id="<%= spree_dom_id(membership) %>" data-hook="taxons_row">
              <td class="move-handle">
                <span class="icon icon-sort handle" style="cursor: pointer"></span>
                <%=  hidden_field_tag('taxon_group_membership[position]['+membership.id.to_s+']', membership.position) %>
              </td>
              <td><%= membership.taxon.name %></td>
              <td><%= taxon_path membership.taxon %></td>
            </tr>
          <% end %>
          <% if @taxon_group_memberships.empty? %>
            <tr data-hook="taxons_none"><td colspan="3"><%= Spree.t(:none) %>.</td></tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.update'), 'refresh', 'submit', {class: 'btn-success'} %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), collection_url, :icon => 'delete' %>
  </div>

  <script>
    $(function() {
      // Make the tablesortable (with updating the position field)
      $('tbody').sortable({
        handle: '.handle',
        update: function(event, ui) {
          $.each($("tbody input"), function(position){
            $(this).val(position);
          });
        }
      });
    });
  </script>

<% end %>

app/views/spree/admin/taxon_groups/_list.html.erb
<table class="table sortable" id='listing_taxon_groups' data-hook>
  <thead>
    <tr data-hook="taxon_groups_header">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:key) %></th>
      <th><%= Spree.t(:taxon_count) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @taxon_groups.each do |taxon_group| %>
      <tr id="<%= spree_dom_id taxon_group %>" data-hook="taxon_groups_row">
        <td><%= taxon_group.name %></td>
        <td><%= taxon_group.key %></td>
        <td><%= taxon_group.taxons.count %></td>
        <td class="actions actions-2 text-right">
          <!-- Edit -->
          <%= link_to_edit taxon_group.id, no_text: true %>

          <!-- Positions -->
          <%= link_to positions_admin_taxon_group_path(taxon_group.id), class: 'btn btn-default btn-sm icon-link with-tip action-positions no-text', 'data-original-title': 'Positions' do %>
            <span class="icon icon-sort"></span>
          <% end %>

          <!-- Delete -->
          <%= link_to_delete taxon_group, no_text: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/taxon_groups/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:edit_taxon_group) %>
<% end %>

<%= render 'form', resource: @taxon_group %>

app/views/spree/admin/taxon_groups/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::TaxonGroup) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_taxon_group), new_object_url, class: "btn-success", icon: 'add', id: 'admin_new_taxon_group_link' %>
<% end %>

<% if @taxon_groups.any? %>
  <div id="list-taxon-groups" data-hook>
    <%= render 'list' %>
  </div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::TaxonGroup)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

app/views/spree/admin/taxon_groups/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_taxon_group, scope: :taxon_group) %>
<% end %>

<%= render 'form', resource: @taxon_group %>

app/views/spree/admin/taxon_groups/positions.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:positions_taxon_group) %>
<% end %>

<%= render 'form_positions', resource: @taxon_group %>